### ISSUE TITLE
RUN_ENV for windows

### ISSUE THREAD

**Issue by sagarnayak** [zupzup/rust-web-configuration-example#1]
How to run cargo with env variable in windows. the RUN_ENV is not recognized.

**Comment by zupzup** [comment]
hey @sagarnayak 

I don't use Windows, but I'm sure if you search for "how to set environment variables in windows" you'll find a way to set it there

**Comment by sagarnayak** [comment]
It's SET <YOUR ENV VALUE>.

 `SET` is to be used before supplying the value.
